### ISSUE TITLE
[Translation] v4

### ISSUE THREAD

**Issue by kotarella1110** [react-hook-form/react-hook-form-website#118]
Help wanted :) 

please help to translate over the website.

we have added two more new features:

https://react-hook-form.com/api#Controller
https://react-hook-form.com/api#ErrorMessage
https://react-hook-form.com/api#control
https://react-hook-form.com/faqs#TestingReactHookForm

- [x] Japanese 🇯🇵  @kotarella1110
- [ ] Korean 🇰🇷  @adhrinae
- [x] Brazilian 🇧🇷 @kevenleone

**Comment by kevenleone** [comment]
Hi !!!

Ok, i'll check and submit new translations soon, seeya.

**Comment by kotarella1110** [comment]
thanks @kevenleone !

**Comment by bluebill1049** [comment]
oh wow, thank you @kevenleone.

looks like @adhrinae is not active anymore.

**Comment by adhrinae** [comment]
@bluebill1049 Oops. I filtered all of my emails from GitHub to a specific folder and haven't checked for a while. had a personal issue.

I think I can finish v4 Translation until this weekend.

**Comment by bluebill1049** [comment]
Oh thanks @adhrinae I hope everything is ok. No pressure on the translation too
