### ISSUE TITLE
Warning: A component is changing an uncontrolled input of type text to be controlled.

### ISSUE THREAD

**Issue by chungweileong94** [react-hook-form/react-hook-form-website#133]
**Describe the bug**
I'm currently using `Controller` with MUI TextField, and it was amazing, but I keep getting this error: `Warning: A component is changing an uncontrolled input of type text to be controlled.`, I have to set an empty string to as the default value to solve the problem, which I think it should done it by default.

**To Reproduce**
1. Use `Controller` with MUI `TextField`
2. Start typing something in the TextField

**Codesandbox link**
https://codesandbox.io/embed/react-hook-form-controlled-warning-demo-l7k6h?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
No error/warning

**Screenshots**
![image](https://user-images.githubusercontent.com/15154097/71796761-459eb000-3086-11ea-8a0c-e4c9e80b9cf0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge (Chromium)
 - Version 79.0.309.58

**Additional context**
A similar issue that i found from `react-hook-form-input`: https://github.com/react-hook-form/react-hook-form-input/issues/31

**Comment by chungweileong94** [comment]
@bluebill1049 Yeah, you got the point, assuming default value might break some input components. 
Will the `defaultValues` in `useForm` overwrites the `defaultvalue` in `Controller`? Since I pretty much wrap every input component with `Controller` with an empty string as `defaultValue`.

**Comment by bluebill1049** [comment]
inline `defaultValue` will overwrite useForm `defaultValues`

**Comment by bluebill1049** [comment]
I have updated the doc :) take a look hopefully make sense.

**Comment by bluebill1049** [comment]
at controller section: https://react-hook-form.com/api#Controller

**Comment by Shelagh-Lewins** [comment]
It seems that if you use 'reset' with Controller, you must explicitly reset each input to avoid an "Uncontrolled inputs" error. It would be great if this could be mentioned in the Controller docs.

**Comment by harshilparmar** [comment]
> inline `defaultValue` will overwrite useForm `defaultValues`

Thanks 😊
