### ISSUE TITLE
State that `isValid` only works with modes: onChange and onBlur

### ISSUE THREAD

**Issue by iamdevlinph** [react-hook-form/react-hook-form-website#151]
I'm not sure if this is stated but it would great to have this beside the `isValid`.

![image](https://user-images.githubusercontent.com/19337229/72707240-f20a8700-3b9a-11ea-878d-9632d0ff0c7f.png)

I can open a PR later for this minor thing if needed.

**Comment by bluebill1049** [comment]
hey @iamdevlinph what's the usage of isValid for onSubmit mode?

**Comment by iamdevlinph** [comment]
I was expecting it to work this way.

When user triggers a submit then the whole form validation is triggered. But if the user only updates a field then that should also update the `formState.isValid`

**Comment by iamdevlinph** [comment]
Since in a sense, the state of the form has been updated because the user updated a field.

**Comment by bluebill1049** [comment]
then that's more of usage for `onChange` validation mode right?

**Comment by bluebill1049** [comment]
happy to adjust for a good reason from UI perspective.

**Comment by bluebill1049** [comment]
or i can update the documentation to reflect this.

**Comment by iamdevlinph** [comment]
Yes. Just an update to the documentation would be nice. Since it was not obvious to me that the `formState.isValid` doesn't work the way I imagined it 😅

No need to make changes to the functionality.

**Comment by bluebill1049** [comment]
you want to submit a PR @iamdevlinph ? would love to see your name at contribution list.

**Comment by iamdevlinph** [comment]
Sure. I'll open one later. Though it's just a minor change lol

**Comment by bluebill1049** [comment]
it's good to have your name on the list, you help quite bit on bug and answering questions at spectrum. thank you

**Comment by iamdevlinph** [comment]
No worries. This package also helped me a lot 👍
