### ISSUE TITLE
"Become a contributor" link lead to 404 error

### ISSUE THREAD

**Issue by nicolastrote** [react-hook-form/react-hook-form-website#159]
To replicate the bug : 
- go on https://github.com/react-hook-form/react-hook-form-website page
- clic on the link "Become a contributor" in the "Contributors" section
<img width="554" alt="Screen Shot 2020-01-31 at 11 16 28 AM" src="https://user-images.githubusercontent.com/20254652/73555632-fa28b900-441b-11ea-84a8-2b65f020c4ac.png">

result : 
- open a new page with 404 error (see print screen)
<img width="628" alt="Screen Shot 2020-01-31 at 11 23 10 AM" src="https://user-images.githubusercontent.com/20254652/73555698-162c5a80-441c-11ea-895d-6a562b5e639f.png">

expected : 
-  open a new page with "how to become a contributor"

**Comment by bluebill1049** [comment]
thanks :) would you like to send a PR for the fix? 

correct link below:
https://github.com/react-hook-form/react-hook-form/blob/master/CONTRIBUTING.md
