### ISSUE TITLE
Incorrect Redux Form example in Library Code Comparison

### ISSUE THREAD

**Issue by chrissantamaria** [react-hook-form/react-hook-form-website#165]
Hi all,

I'm not super familiar with Redux Form, but this code snippet from the Library Code Comparison section of the homepage caught my attention:

https://github.com/react-hook-form/react-hook-form-website/blob/eb3b125d5f91818419aebfcef4a7d669fe3cf3a9/src/components/codeExamples/reduxFormCode.ts#L9-L13

Shouldn't this just be checking `values.username`, not `values.username.length`? Happy to make PR if that's the case - just wanted to check first.

**Comment by bluebill1049** [comment]
yes, your right please send a PR. 🙏

**Comment by chrissantamaria** [comment]
Done! #166

**Comment by bluebill1049** [comment]
thank you for your contribution @chrisparton1991

**Comment by chrissantamaria** [comment]
You mean @chrissantamaria? :stuck_out_tongue:

**Comment by bluebill1049** [comment]
Oops 😐

**Comment by chrisparton1991** [comment]
You're welcome Bill, always happy to help 😂

**Comment by bluebill1049** [comment]
LOL 👍
