### ISSUE TITLE
Performance issue on API page

### ISSUE THREAD

**Issue by gilbsgilbs** [react-hook-form/react-hook-form-website#177]
Following up https://github.com/react-hook-form/react-hook-form-website/pull/176#issuecomment-583782153

The [API](https://react-hook-form.com/api#register) page of the website is slow. In particular, toggling the two radio buttons under `Register options` section induces a noticeable lag of a few milliseconds on both Firefox and Chromium.

See repro screen capture as requested in #176 : https://drive.google.com/file/d/16Z5AdlqTbikv_72mKcgoFM4yPZDKw6z3/view

Keep up the great work. Thanks 👍

**Comment by bluebill1049** [comment]
fixed! thanks @gilbsgilbs ❤️ give it a try in 5 mins after deployment

**Comment by bluebill1049** [comment]
give me back my lighting fast website 😭haha

**Comment by bluebill1049** [comment]
closing now :)

**Comment by gilbsgilbs** [comment]
FYI, just tested this out and it's way better now, in both normal and private browsing modes :ok_hand: .

**Comment by bluebill1049** [comment]
thanks @gilbsgilbs for the confirmation
