### ISSUE TITLE
"Live Demo" section: Touched column remains always empty

### ISSUE THREAD

**Issue by ikornienko** [react-hook-form/react-hook-form-website#184]
On the https://react-hook-form.com/ website the "Live Demo" section at the bottom doesn't populate touched fields in the "Touched" column.

![Screenshot 2020-02-18 at 21 33 54](https://user-images.githubusercontent.com/477269/74804914-80575300-5296-11ea-9a3a-d3afad9b3404.png)

**Comment by ikornienko** [comment]
I'm totally new to `react-hook-form` (currently a user of `redux-form`, that's how I ended up on a website looking for alternatives). So, out of curiosity, I'll see if I can quickly fix the issue myself, as it's probably something simple :)

**Comment by bluebill1049** [comment]
oops thanks i will take a look tonight (if you haven't)

**Comment by ikornienko** [comment]
Will submit a PR in a moment :)
