### ISSUE TITLE
improve validationResolver documentation

### ISSUE THREAD

**Issue by anilanar** [react-hook-form/react-hook-form-website#192]
**Describe the bug**
See https://codesandbox.io/s/silly-cdn-95w82

- Try commenting out `validationResolver` option and submitting the form logs the expected output.
- Try using with `validationResolver` option and it will not submit form fields correctly (only the first submit is correct?). It seems `validationResolver` is not being passed the full `values` object.

**Comment by bluebill1049** [comment]
moving it under website to improve the doc
