### ISSUE TITLE
useFieldArray: Unable to call remove and append/insert on the same event handler

### ISSUE THREAD

**Issue by matheusffatg** [react-hook-form/react-hook-form-website#212]
**Describe the bug**
When calling remove and append, the expected behaviour would be that one item is removed and one item is appended, but the result is that the removed item is still in the list.
Also when calling remove and insert it throws an exception.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-qkpif
2. Click on "replace", which removes first item and append a new one.
3. 2 items remain in the array, but expected one

* try "insert at (max 3)" and you will see the exception.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-qkpif

**Expected behavior**
should be able to call any of these methods on the same event handler and being able to update field array at will.

**Comment by activenode** [comment]
@matheusffatg I had the same problem and I ended up using `setValue` which works fine in combination with `useFieldArray` apparently.
