### ISSUE TITLE
Unexpected behavior handling errors in Gatsby

### ISSUE THREAD

**Issue by michaeljblum** [react-hook-form/react-hook-form-website#214]
Errors don't seem to be handled correctly in Gatsby. Upon submission of form, errors aren't being rendered as they are in Create React App.

Here are two sandboxes with largely identical code (taken from the RHF docs), one in CRA and one using Gatsby:

**CRA:** https://codesandbox.io/s/rough-cookies-6g7jp

**Gatsby:** https://codesandbox.io/s/elated-hooks-dsls1

Upon submission of CRA form, errors are rendered, upon submission of Gatsby form, nothing is rendered and logging errors yields an empty object.

**Comment by bluebill1049** [comment]
? it's working fine here...

**Comment by bluebill1049** [comment]
<img width="625" alt="Screen Shot 2020-03-08 at 9 16 46 am" src="https://user-images.githubusercontent.com/10513364/76153248-903bb780-611d-11ea-8f1d-e25ee60ffc09.png">
<img width="587" alt="Screen Shot 2020-03-08 at 9 16 49 am" src="https://user-images.githubusercontent.com/10513364/76153251-92057b00-611d-11ea-85b2-e213eacefc25.png">

**Comment by michaeljblum** [comment]
Weird, I got the same behavior in my project as with this codesandbox - it wasn't working upon save but upon page reload it works as expected. Odd. Thanks, though!
