### ISSUE TITLE
Custom hook addition to the docs (useYupValidationResolver) 

### ISSUE THREAD

**Issue by thexpand** [react-hook-form/react-hook-form-website#225]
This is a hook for easy integration of yup as a validation method, using a validation resolver. The hook returns a memoized callback that can act as a validation resolver for `useForm` hook:

```
import { useCallback } from 'react';

const useYupValidationResolver = validationSchema =>
    useCallback(
        async data => {
            try {
                const values = await validationSchema.validate(data, {
                    abortEarly: false,
                });

                return {
                    values,
                    errors: {},
                };
            } catch (errors) {
                return {
                    values: {},
                    errors: errors.inner.reduce(
                        (allErrors, currentError) => ({
                            ...allErrors,
                            [currentError.path]: {
                                type: currentError.type ?? 'validation',
                                message: currentError.message,
                            },
                        }),
                        {},
                    ),
                };
            }
        },
        [validationSchema],
    );

export default useYupValidationResolver;
```

It can be used in a form like this:
- define a memoized validation schema (or define it outside your component if you don't have any dependencies)
- use the custom hook, by passing the validation schema
- pass the validation resolver to the `useForm` hook
```
    const validationSchema = useMemo(
        () =>
            yup.object({
                firstName: yup.string().required('Required'),
                lastName: yup.string().required('Required'),
            }),
        [],
    );

    const validationResolver = useYupValidationResolver(validationSchema);

    const form = useForm({ validationResolver });
```

**Comment by bluebill1049** [comment]
This is really cool!

**Comment by bluebill1049** [comment]
i will add this into the advance section of the doc.

**Comment by CBurrows87** [comment]
Hi, is there an example of this in use? I am currently trying to validate a dynamic form using json, and i think this is what im looking for validating? 

   forename: {
      type: "text",
      key: "forename",
      name: "forename",
      label: "Forename",
      tooltipText: "this is a popup",
      placeholder: "",
      validation: [
        {
          rule: "IsRequired",
          message: "Please enter your forename",
        },
      ],
    },

This is an example of the json i am using, and want the validation bit to be hooked into my form using yup. 

Am i right in thinking your hook is the right approach?

**Comment by bluebill1049** [comment]
@CBurrows87 check out the `resolver` you can write your own validation logic
