### ISSUE TITLE
Can't see the demo video toggles in light mode

### ISSUE THREAD

**Issue by ilyakam** [react-hook-form/react-hook-form-website#261]
When you toggle the website to "light mode," it is impossible to read the "React Web" video toggle because it appears white-on-white, as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/183227/81756684-464eb500-9471-11ea-821c-b10465f8fee4.png)

Tested on Firefox v76.0.1 and Chrome v81.0.4044.138 on macOS v10.15.4

**Comment by bluebill1049** [comment]
oops, would you be able to send a PR to fix this, please? similar to this PR: https://github.com/react-hook-form/react-hook-form-website/commit/ae12ebf4e4c45a4b0ae3d8b104308f4bd3c2ad15

**Comment by ilyakam** [comment]
It looks great, thanks!
