### ISSUE TITLE
the faqs link is broken on the footer

### ISSUE THREAD

**Issue by ricardocanelas** [react-hook-form/react-hook-form-website#27]
![Screenshot 2019-10-18 at 14 56 35](https://user-images.githubusercontent.com/663151/67116923-d49ed900-f1b7-11e9-990a-10f8da9c2d11.png)

![Screenshot 2019-10-18 at 14 57 59](https://user-images.githubusercontent.com/663151/67116932-d799c980-f1b7-11e9-9ef1-648a78eab24f.png)

![Screenshot 2019-10-18 at 14 58 34](https://user-images.githubusercontent.com/663151/67116936-da94ba00-f1b7-11e9-888d-690dc2bbba61.png)

**Comment by bluebill1049** [comment]
thanks!
