### ISSUE TITLE
[Translation] Korean 

### ISSUE THREAD

**Issue by jiyeonseo** [react-hook-form/react-hook-form-website#42]
The main project process is here : https://github.com/react-hook-form/react-hook-form/projects/1
Just want to make this progress more visible, to avoid any conflicts and to review together for better quality 😉

Now, we have four parts to go :  
- [x] API - @jiyeonseo - I'm working on this 
- [x] Advanced
- [x] builder
- [x] faq

Let's leave a comment which part you want to work :)

**Comment by adhrinae** [comment]
FAQ & Advanced are on me ✋

**Comment by bluebill1049** [comment]
thanks, @jiyeonseo and @adhrinae <3

**Comment by bluebill1049** [comment]
I have updated the board: https://github.com/react-hook-form/react-hook-form/projects/1

**Comment by purelledhand** [comment]
I want to contribute by translating `builder` part 🙏🏻😊

**Comment by bluebill1049** [comment]
thank you @purelledhand 

The Korean community is so nice and kind!! <3

**Comment by bluebill1049** [comment]
updated the board: https://github.com/react-hook-form/react-hook-form/projects/1

I think we gonna have Korean version go live soon 🤘🇰🇷❤️

**Comment by bluebill1049** [comment]
@adhrinae can you please update FAQ section? I have added a comparison table for different forms  libs.

**Comment by bluebill1049** [comment]
<img width="995" alt="Screen Shot 2019-10-29 at 11 07 31 am" src="https://user-images.githubusercontent.com/10513364/67727140-560a2d00-fa3c-11e9-8507-5c5807ea9b9e.png">

**Comment by adhrinae** [comment]
OK. I'll upload a PR when it's done.

**Comment by bluebill1049** [comment]
thanks very much @adhrinae

**Comment by bluebill1049** [comment]
hello @jiyeonseo hope you had a great week, just wondering what's your progress on API page (the most complicated page and the final page too...) If you have done some work please create a PR maybe I and others can assist the translation.  very keen to get the Korean documentation to go live :) Not putting down any pressure on you, I am here to help and I am sure others will do the same 👍 

cheers
bill

**Comment by bluebill1049** [comment]
looks like @jiyeonseo is busy, maybe we can help out next week on the API page if she is still not replying. I can help translate pages with some external service (google translate) and get your guys to review.

**Comment by jiyeonseo** [comment]
Hey @bluebill1049 ! Sorry for the late reply. had crazy busy week 😭I've almost done on API part and polishing now. Let me PR tmr :) Thanks for your patience.

**Comment by bluebill1049** [comment]
oh, thank you very much @jiyeonseo no worries at all, much appreciated your effort <3

**Comment by bluebill1049** [comment]
Thank you all! <3 Really appreciated your works.

@jiyeonseo, @iamchanii, @purelledhand and @adhrinae

<img width="875" alt="Screen Shot 2019-11-03 at 9 06 16 pm" src="https://user-images.githubusercontent.com/10513364/68083540-d508c680-fe7d-11e9-8be4-19b1ca013e7e.png">

**Comment by jiyeonseo** [comment]
Finally 🥳❤️

**Comment by bluebill1049** [comment]
@iamchanii @jiyeonseo @purelledhand do you guys have twitter account? I would like to tag you guys when I am posting up the Korean documentation. (I already have @adhrinae)

**Comment by purelledhand** [comment]
> @iamchanii @jiyeonseo @purelledhand do you guys have twitter account? I would like to tag you guys when I am posting up the Korean documentation. (I already have @adhrinae)

@bluebill1049 I don't have one :) Thanks.😊

**Comment by iamchanii** [comment]
@bluebill1049 I don't have. thanks. also thanks to all contributors :)

**Comment by jiyeonseo** [comment]
> @iamchanii @jiyeonseo @purelledhand do you guys have twitter account? I would like to tag you guys when I am posting up the Korean documentation. (I already have @adhrinae)

https://twitter.com/seojeee this is mine ☺️ Thanks~
