### ISSUE TITLE
[Translation] Japanese

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/react-hook-form-website#43]
The main project process is here : https://github.com/react-hook-form/react-hook-form/projects/1

a Japanese version of the website
- [x] home @kotarella1110 
- [x] getStarted @kotarella1110 
- [x] api @kotarella1110 
- [x] advanced @kotarella1110 
- [x] builder @kotarella1110 
- [x] faq https://github.com/dowdiness
- [x] nav @kotarella1110 
- [x] generic @kotarella1110

**Comment by bluebill1049** [comment]
@kotarella1110 I believe https://github.com/dowdiness is working on FAQ just an FYI

**Comment by kotarella1110** [comment]
@bluebill1049 That is very helpful!
@dowdiness Thanks :sparkles:

**Comment by bluebill1049** [comment]
thanks very much for your hard-working @kotarella1110 I really appreciated it and so do the Japanese developers around the world :)

**Comment by bluebill1049** [comment]
Once FAQ is completely dowdiness, we can go live with Japanese documentation!

**Comment by bluebill1049** [comment]
hmmm, FYI @kotarella1110 the other guy didn't reply anything around the FAQ page... so I have no idea what's his progress or whether he is working on it at all.

**Comment by dowdiness** [comment]
Hi. Sorry for letting you guys wait without reply. I will translate FAQ page. Maybe translation will be done today.

**Comment by bluebill1049** [comment]
Oh my god! thank you @dowdiness 
FYI @kotarella1110

**Comment by kotarella1110** [comment]
Completed! 🎉 

🇯🇵 https://react-hook-form.com/jp/
