### ISSUE TITLE
I suggest to add « react-hook-form » vs « formik 2.0 » section in faqs

### ISSUE THREAD

**Issue by harobed** [react-hook-form/react-hook-form-website#50]
Hi,

I suggest to add « react-hook-form » vs « [formik 2.0](https://www.npmjs.com/package/formik) » section in [faqs](https://react-hook-form.com/faqs).

Best regards,
Stéphane

**Comment by harobed** [comment]
> What about the lib learning curve? IMHO react hook form is very easy to use

@bluebill1049 yes, `react-hook-form` learning curve is lower that `formik`.

**Comment by harobed** [comment]
Thanks ❤️ @bluebill1049

**Comment by bluebill1049** [comment]
my pleasure and thank you for your suggestion too :)
