### ISSUE TITLE
Typo in repository description

### ISSUE THREAD

**Issue by purelledhand** [react-hook-form/react-hook-form-website#65]
![image](https://user-images.githubusercontent.com/13747937/68118457-6b52f000-ff43-11e9-9637-e2c4bd781f52.png)

2 typos are in the repository description.😊
I think it could be changed to `React Hook Form official website`

**Comment by bluebill1049** [comment]
OMG...

**Comment by bluebill1049** [comment]
😣thank you @purelledhand

**Comment by bluebill1049** [comment]
<img width="598" alt="Screen Shot 2019-11-04 at 10 53 25 pm" src="https://user-images.githubusercontent.com/10513364/68119112-efae6e80-ff55-11e9-9c0d-5095e5ac5946.png">

FYI : )
