### ISSUE TITLE
Smart form component form documentation not working

### ISSUE THREAD

**Issue by mr-bjerre** [react-hook-form/react-hook-form-website#70]
The smart form component from the documentation is not working: https://codesandbox.io/s/react-hook-form-smart-form-component-eqb3n

In the `Form` it does not like `...methods`. It yields `object is not a function`.

Also; how do you write the `Form` component in typescript? It does not accept `props` on `child` object.

**Comment by bluebill1049** [comment]
thanks @mr-bjerre codesandbox have been fixed, will update the website as well.

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#TypeScript

**Comment by bluebill1049** [comment]
I haven't tried to write that form component in typescript. it may be a bit tricky to write that

**Comment by mr-bjerre** [comment]
Yeh I figured. It would also be pretty cool to embed validation rules into the setup. I guess it could go into either the Form as props or the individual UI components.

And thanks a bunch for a great library (and extremely quick response)

**Comment by bluebill1049** [comment]
yeah, that's the pattern I have set up at work, but we are not using typescript, so I have bit extra freedom there :) it did work out pretty well with the help from form context. Basically any inputs sit under SmartForm data and validation will apply directly, for something bit more complicated we use FormContext to solve them individually. (https://react-hook-form.com/advanced-usage#ConnectForm)

**Comment by bluebill1049** [comment]
going to close it here for fixing the website :) in terms of typescript for smart form hopefully someone can figure out a solution :) it's sitting in the spectrum as well

**Comment by mr-bjerre** [comment]
Do you mind opening this again?

I'd love to have a typescript version of the smart form.

**Comment by bluebill1049** [comment]
Sure, let's see if community can help out this one. I will attach a help tag.

**Comment by mr-bjerre** [comment]
Cool.

I also noted that input elements like `<input />` has to be an immediate child of `<Form>`. You can't have them nested.

**Comment by bluebill1049** [comment]
That's correct. for deep nest consider to use ConnectForm, which is in the doc as well

**Comment by bluebill1049** [comment]
(cleaning up issues) This issue is getting really "old", i am going to close this issue, but feel free to leave your answer here.

**Comment by pandaniell** [comment]
```typescript
import React, { createElement, ReactElement } from "react";
import { DeepPartial, OnSubmit, useForm } from "react-hook-form";

interface IFormProps<T> {
  defaultValues?: DeepPartial<T>;
  onSubmit: OnSubmit<T>;
}

export function Form<T>({
  defaultValues,
  children,
  onSubmit
}: IFormProps<T> & { children: ReactElement | ReactElement[] }) {
  const { register, handleSubmit } = useForm<T>({ defaultValues });

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {Array.isArray(children)
        ? children.map(child => {
            return child.props.name
              ? createElement(child.type, {
                  ...{
                    ...child.props,
                    register,
                    key: child.props.name
                  }
                })
              : child;
          })
        : children}
    </form>
  );
}
```
I was able to make use of the smart form in TypeScript using this, the usage is as follows:
**Input (I'm using a UI Component library for this)**
```typescript
import { Input as ChakraInput, InputProps } from "@chakra-ui/core";
import React from "react";
import { FormContextValues } from "react-hook-form";

interface IInputProps {
  register: FormContextValues["register"];
  name: string;
}

export const Input = ({
  register,
  name,
  ...props
}: Partial<IInputProps & InputProps<HTMLInputElement>>) => (
  <ChakraInput name={name} ref={register} {...props} />
);
```
**Form setup (passing in the generic gives Type safety for defaultValues)**
```typescript
interface UserGuildInput {
  prefix: string
}

<Form<UserGuildInput>
  defaultValues={{ prefix: data.guild.prefix }}
  onSubmit={onSubmit}
>
  <Input name="prefix" />
  <Input name="language" />

  <button type="submit">submit</button>
</Form>
```
I'm not too experienced with TypeScript so input is welcome :)

**Comment by bluebill1049** [comment]
hey @pandaniell this is really awesome. would be able to create a TS codesandbox with this, i can link this into our website.

**Comment by willianfalbo** [comment]
> ```ts
> import { FormContextValues } from "react-hook-form";
> ```

Hey @pandaniell / @bluebill1049 I wasn't able to get this line working. How can I fix it? I'm using the lasted version of the lib.

**Comment by bluebill1049** [comment]
> > ```ts
> > import { FormContextValues } from "react-hook-form";
> > 
> > ...
> >   register: FormContextValues["register"];
> > ...
> > ```
> 
> Hey @pandaniell / @bluebill1049 I wasn't able to get this line working. How can I fix it? I'm using the lasted version of the lib.

https://react-hook-form.com/ts#UseFormMethods

**Comment by OuuGiii** [comment]
Just want to point out that the smart Form component doesn't work if you have an element that doesn't contain the prop "name" or any prop at all inside of the Form component, as it will throw an error like this:
![image](https://user-images.githubusercontent.com/90676925/158601436-bb55654e-48cc-44b4-a175-1e31b9113a84.png)

To make it possible I change the code to check the type of the component inside of the form component by creating a simple method "childIsAFormComponent", like this:
```
import React from 'react'
import { useForm } from 'react-hook-form'

const Form = ({ defaultValues, children, onSubmit }) => {
  const methods = useForm({ defaultValues })
  const { handleSubmit } = methods

  const childIsAFormComponent = (NameOfComponent) => {
    if (
      NameOfComponent === 'Input' ||
      NameOfComponent === 'Select' ||
      NameOfComponent === 'TextArea' ||
      NameOfComponent === 'Checkbox'
    ) {
      return true
    }
    return false
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {React.Children.map(children, (child) =>
        childIsAFormComponent(child?.type?.name)
          ? React.createElement(child.type, {
              ...{
                ...child.props,
                register: methods.register,
                key: child.props.name
              }
            })
          : child
      )}
    </form>
  )
}

export default Form
```

With this solutions you still need the input elements to be a direct child, but you can have other components in it as well (like divs and buttons), like this:
```
<Form onSubmit={onSubmit}>
  <Input name="firstName" />
  <Input name="lastName" />
  <Select name="gender" options={["female", "male", "other"]} />
  <div>
    <span>Some cool stuff here ...</span>
  </div>
  <button type="submit">Submit</button>
</Form>
```

Suggestions for improving this are welcome.
