### ISSUE TITLE
Can you provide an example of an autosave form?

### ISSUE THREAD

**Issue by stunaz** [react-hook-form/react-hook-form-website#74]
**Describe the solution you'd like**
An example of an autosave form with debounce

**Comment by bluebill1049** [comment]
someone made a hook!

https://github.com/tiaanduplessis/react-hook-form-persist :)

**Comment by nprasanth-fs** [comment]
> ```
> const { watch } = useForm();
> 
> const data = watch();
> 
> useEffect(() => {
>   save(data)
> }, data)
> ```
> 
> also please consider asking questions in the spectrum channel next time as well :) thanks



> ```
> const { watch } = useForm();
> 
> const data = watch();
> 
> useEffect(() => {
>   save(data)
> }, data)
> ```
> 
> also please consider asking questions in the spectrum channel next time as well :) thanks

Hi , i am getting save is not defined @bluebill1049

**Comment by emaillenin** [comment]
`watch` is being fired twice on the first render. How can we prevent this?

**Comment by bluebill1049** [comment]
> `watch` is being fired twice on the first render. How can we prevent this?

codesandbox?
