### ISSUE TITLE
Form builder with optional third-party UI library code generation.

### ISSUE THREAD

**Issue by saisandeepvaddi** [react-hook-form/react-hook-form-website#76]
The form builder is a great feature.
I'm just requesting to take it another level by providing option to generate code according to a third-party library.

For example, I use ant. If I use form builder and copy code, I still have to change the fields according to ant specific fields API. If there is someway I can choose what library I use, and the code sample has code with ant's `Input` field and they are registered like you show in `Work with UI library` section.

I know there are a ton of UI libraries, but this feature request is just a thought.

**Comment by bluebill1049** [comment]
It sounds like a great idea! the tricky part is to deal with all the lib's component Props, HTML standstill but those external UI can change anytime, which can make maintaining it hard.

**Comment by saisandeepvaddi** [comment]
Agreed.
