### ISSUE TITLE
https://codesandbox.io/s/6j1760jkjk example is not going down in the counter when removes element

### ISSUE THREAD

**Issue by esuarezz** [react-hook-form/react-hook-form-website#81]
https://codesandbox.io/s/6j1760jkjk

Solution:

Change removeFriend method for the next one:
  const removeFriend = index => () => {
    setIndexes(prevIndexes => [...prevIndexes.filter(item => item !== index)]);
    setCounter(prevCounter => prevCounter - 1);
  };

**Comment by bluebill1049** [comment]
good point! thanks fixed.
